### PR TITLE
Added Movie Info project

### PR DESCRIPTION
**Pull request by gopivaibhav**
Please Accept my PR under Hacktoberfest label :)
Also to preview my project use this [link](http://vaibhav-info.herokuapp.com/)

### CODE REVIEW

**Comment by rahulray11** [comment]
it will take some time to update in Hacktoberfest site.

**Comment by rahulray11** [comment]
Whenever I try to login . It is showing wrong password please check it once.

**Comment by gopivaibhav** [comment]
@rahulray11 Sir, can you please check my PR and provide hacktoberfest-accepted label ?

**Comment by rahulray11** [comment]
Ya sure

**Pull request merged**
