### PR TITLE
Api based Advice Generaotor it is my first PR please accept it

### PR DESCRIPTION
**Pull request by shivam-jha2712**
It is my first ever pr if merged successfully and I am looking forward to doing more such contribution and I have even followed every single instruction on the readme. I have both starred and Forked the repository so please di let me know after you take the necessary decision.

### CODE REVIEW

**Review by rahulray11 — APPROVED** [review]

**Comment by rahulray11** [comment]
you have done a good job. No need to worry it will update on hacktober fest site within 20min.

**Comment by rahulray11** [comment]
but upload all files please

**Comment by rahulray11** [comment]
you are only created a folder

**Comment by shivam-jha2712** [comment]
How to add I am unable to do so? Please help me out. I can not find the files

**Comment by shivam-jha2712** [comment]
I can not see my folder on the main branch and I am unable to add any files so what should I do ?? I have added the files in the zip form in the previous comment if you could guide me though

**Comment by rahulray11** [comment]
don't upload zip files. upload all your files in your branch then again
pull request

**Comment by shivam-jha2712** [comment]
In the branch, there are no zip files if you could refer to the most recent pull request made #51

**Comment by shivam-jha2712** [comment]
I have added all the files in the new pull request number 51 if you could
just check it once. I am really sorry to disturb you but as its my first PR
and fest So i am getting confused and anxious as prior to this 4 of my PR
were in an excluded project. Henceforth I want at least this one to be
converted and I would really appreciate it if cold guide me through this
process

**Comment by rahulray11** [comment]
It's ok ,I can understand your situation don't worry it will be updated on your hacktober fest site and it will not showing  in excluded project. Just keep contributing and keep calm.

**Comment by rahulray11** [comment]
I have merged your PR.  
tell me it's showing in progress or not?

**Comment by shivam-jha2712** [comment]
Yes it has been accepted. Thank you

**Comment by rahulray11** [comment]
nice to e-meet you. 
btw you are in which year?

**Comment by shivam-jha2712** [comment]
I am in 2nd year 3rd sem

**Comment by rahulray11** [comment]
ok If you want to know anything in future just drop a message. I will surely reply you as soon as possible.

**Comment by rahulray11** [comment]
https://www.linkedin.com/in/rohitray042/  
this is my linkedin profile u can message me on linkedin if anything urgent.

**Comment by shivam-jha2712** [comment]
Thank you for your response and such helping nature. I bet I have been a
pain in the butt.😅 Sorry for that and again thanks for the help means a
lot

**Pull request merged**
