### PR TITLE
feat: click on synonym to navigate to synonym's definition

### PR DESCRIPTION
**Pull request by simmiggrwl**
added feature in dictionary app

### CODE REVIEW

**Comment by simmiggrwl** [comment]
(hacktoberfest)

**Review by rahulray11 — APPROVED** [review]

**Comment by simmiggrwl** [comment]
Hey, was this not a part of hacktoberfest because my hacktoberfest page has
not been updated?

**Comment by rahulray11** [comment]
It's take 30min. To update

**Comment by rahulray11** [comment]
Refresh the hacktoberfest page 2 or 3times.

**Comment by rahulray11** [comment]
Is it updated now or not?

**Comment by simmiggrwl** [comment]
It is there in the ‘in progress’ field but now in the total completed one

**Comment by rahulray11** [comment]
Great .Thanks for contributing here

**Pull request merged**
